# Generated by Django 5.1.7 on 2025-03-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='cancellation_window',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
