# Generated by Django 5.1.7 on 2025-03-16 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_experience_cancellation_window_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='refund_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Percentage refund for cancellations within the window', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='cancellation_window',
            field=models.PositiveIntegerField(default=24, help_text='Hours before experience when cancellation is allowed'),
        ),
    ]
